Name: Flutter Build (AAB & APK)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '[:space:]' | base64 --decode > android/app/upload-keystore.jks

      # 1. بناء نسخة المتجر (Bundle)
      - name: Build Release Bundle (AAB)
        run: flutter build appbundle --release

      # 2. بناء نسخة التجربة (APK)
      - name: Build Release APK
        run: flutter build apk --release

      # 3. رفع الـ AAB في أرشيف لوحده
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aksab-Captain-AAB
          path: build/app/outputs/bundle/release/app-release.aab

      # 4. رفع الـ APK في أرشيف لوحده
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aksab-Captain-APK
          path: build/app/outputs/flutter-apk/app-release.apk
