name: Flutter Build (APK Only)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '[:space:]' | base64 --decode > android/app/upload-keystore.jks

      # 🟢 [تعطيل مؤقت لنسخة المتجر]
      # - name: Build Release Bundle (AAB)
      #   run: flutter build appbundle --release

      # 1. بناء نسخة التجربة (APK) - هي دي اللي بنركز عليها حالياً
      - name: Build Release APK
        run: flutter build apk --release

      # 🟢 [تعطيل مؤقت لرفع ملف المتجر]
      # - name: Upload AAB Artifact
      #   uses: uses/upload-artifact@v4
      #   with:
      #     name: Aksab-Captain-AAB
      #     path: build/app/outputs/bundle/release/app-release.aab

      # 2. رفع الـ APK في أرشيف لوحده (للتجربة والاختبار المغلق)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aksab-Captain-APK
          path: build/app/outputs/flutter-apk/app-release.apk
